In [11]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from decouple import config
import time
import pandas as pd 

# Inicializar el driver de Selenium
driver = webdriver.Chrome()

# Ir a la página de inicio de LinkedIn
driver.get("https://www.linkedin.com/uas/login/")


user =config("USER_LKN")
clave =config("PASS_LKN")

# Encontrar el campo de inicio de sesión y enviar credenciales
username = driver.find_element(By.ID,"username")
username.send_keys(user)
password = driver.find_element(By.ID,"password")
password.send_keys(clave)

time.sleep(9)

# Hacer clic en el botón de inicio de sesión
boton=driver.find_element(By.CLASS_NAME,"btn__primary--large.from__button--floating")
boton.click()

time.sleep(9)
# Ir a la página de búsqueda de trabajos
driver.get("https://www.linkedin.com/jobs/")
time.sleep(9)

# Encontrar el campo de búsqueda y enviar términos de búsqueda
search_field = driver.find_element(By.CLASS_NAME,"jobs-search-box__text-input.jobs-search-box__keyboard-text-input")
search_field.send_keys("Data")
search_field.send_keys(Keys.ENTER)
time.sleep(9)

job_elements = driver.find_elements(By.CSS_SELECTOR,"[class*='job-card-container']")
jobs = []

# Iterar sobre los elementos de las ofertas de trabajo
for job_element in job_elements:
    title_elements = job_element.find_elements(By.CSS_SELECTOR,".disabled ember-view job-card-container__link job-card-list__title")
    company_elements = job_element.find_elements(By.CSS_SELECTOR,".job-card-container__link job-card-container__company-name ember-view")
    location_elements = job_element.find_elements(By.CSS_SELECTOR,"[class*='metadata-item']")
    title = title_elements[0].text if title_elements else None
    company = company_elements[0].text if company_elements else None
    location = location_elements[0].text if location_elements else None
    jobs.append({"title": title, "company": company, "location": location})


# Almacenar los datos en un DataFrame de Pandas
jobs_df = pd.DataFrame(jobs)

In [18]:
jobsX= pd.DataFrame(jobs)
jobsX

   title company                location
0   None    None  Lima, Perú (En remoto)
1   None    None                    None
2   None    None                    None
3   None    None                    None
4   None    None  Lima, Perú (En remoto)
5   None    None                    None
6   None    None                    None
7   None    None                    None
8   None    None                    None
9   None    None                    None
10  None    None                    None
11  None    None                    None
12  None    None  Lima, Perú (En remoto)
13  None    None                    None
14  None    None                    None
15  None    None                    None
16  None    None  Lima, Perú (En remoto)
17  None    None                    None
18  None    None                    None
19  None    None                    None
20  None    None                    None
21  None    None                    None
22  None    None                    None
23  None    None  Lima, Perú (En remoto)
24  None    None                    None
25  None    None                    None
26  None    None                    None
27  None    None  Lima, Perú (En remoto)
28  None    None                    None
29  None    None                    None
30  None    None                    None
31  None    None                    None
32  None    None                    None
33  None    None                    None
34  None    None                    None
35  None    None                    None
36  None    None                    None
37  None    None                    None
38  None    None                    None
39  None    None                    None
40  None    None                    None
41  None    None                    None
42  None    None                    None
43  None    None                    None
44  None    None                    None
45  None    None                    None
46  None    None                    None
47  None    None                    None
48  None    None                    None
49  None    None                    None
50  None    None                    None
51  None    None                    None
52  None    None                    None

In [12]:
jobs_df = jobs_df[jobs_df.title.notnull()]

In [13]:
jobs_df

Empty DataFrame
Columns: [title, company, location]
Index: []

In [14]:
TITULO
class="disabled ember-view job-card-container__link job-card-list__title"
COMPAÑIA
class="job-card-container__link job-card-container__company-name ember-view"

SyntaxError: invalid syntax (13571772.py, line 2)